name: Backend Tests

on:
  workflow_dispatch:  # Enables manual triggering
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_HOST: dpg-cpn17duehbks7380eta0-a
      DB_NAME: berkay_db
      DB_USERNAME: berkay_db_user
      DB_PASSWORD: mrS7KP3auNE70LJcC042UMtX33mJKrTY
      DB_PORT: 5432

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ env.DB_NAME }}
          POSTGRES_USER: ${{ env.DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
        options: >-
          --health-cmd="pg_isready -U $POSTGRES_USER" 
          --health-interval=10s 
          --health-timeout=10s 
          --health-retries=10

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'  # Options: 'adopt', 'zulu', 'temurin', etc.

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Wait for PostgreSQL
        env:
          POSTGRES_USER: ${{ env.DB_USERNAME }}
        run: |
          until pg_isready -h ${{ env.DB_HOST }} -U $POSTGRES_USER -p ${{ env.DB_PORT }}; do
            echo "$(date) - waiting for postgres...";
            sleep 5;
          done

      - name: Set up database URL
        run: echo "DB_URL=jdbc:postgresql://${{ env.DB_HOST }}:${{ env.DB_PORT }}/${{ env.DB_NAME }}" >> $GITHUB_ENV

      - name: Build with Gradle
        env:
          DB_URL: ${{ env.DB_URL }}
          DB_USERNAME: ${{ env.DB_USERNAME }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
        run: ./gradlew build

      - name: Run tests
        env:
          DB_URL: ${{ env.DB_URL }}
          DB_USERNAME: ${{ env.DB_USERNAME }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
        run: ./gradlew test
