name: Backend Tests

on:
  workflow_dispatch:  # Dies ermöglicht die manuelle Ausführung
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: berkay_db
          POSTGRES_USER: berkay_db_user
          POSTGRES_PASSWORD: mrS7KP3auNE70LJcC042UMtX33mJKrTY
        options: >-
          --health-cmd="pg_isready -U berkay_db_user" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Wait for PostgreSQL
        env:
          POSTGRES_USER: ${{ secrets.DB_USERNAME }}
        run: |
          until pg_isready -h localhost -U $POSTGRES_USER; do
            echo "$(date) - waiting for postgres...";
            sleep 2;
          done

      - name: Set up database URL
        run: echo "DB_URL=jdbc:postgresql://localhost:5432/berkay_db" >> $GITHUB_ENV

      - name: Build with Gradle
        env:
          DB_URL: ${{ env.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: ./gradlew build

      - name: Run tests
        env:
          DB_URL: ${{ env.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: ./gradlew test
